<?xml version='1.0'?>

<robot name="myrobot" 
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="simulation" default="false"/>

  <xacro:if value="$(arg simulation)">
    <xacro:include filename="$(find racer_description)/urdf/racer_plugins.gazebo" />
  </xacro:if>
  <xacro:include filename="$(find racer_description)/urdf/racer_macros.xacro" />

  <xacro:property name="cameraSizeL" value="0.03"/>
  <xacro:property name="cameraSizeB" value="0.03"/>
  <xacro:property name="cameraSizeH" value="0.17"/>
  <xacro:property name="cameraMass" value="0.1"/>

  <xacro:property name="hokuyoSize" value="0.1"/>
  <xacro:property name="hokuyoMass" value="0.1"/>

  <xacro:property name="bodySizeL" value="0.49"/>
  <xacro:property name="bodySizeB" value="0.18"/>
  <xacro:property name="bodySizeH" value="0.1"/>
  <xacro:property name="bodyMass" value="3.5"/>

  <link name="base_link" />

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0.05" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="chassis" />
  </joint>

  <!--  Body  -->
  <link name='chassis'>
    <inertial>
      <mass value="${bodyMass}"/>
      <origin xyz="0 0 ${wheel_height/2}" rpy=" 0 0 0"/>
      <box_inertia m="${bodyMass}" l="${bodySizeL}" b="${bodySizeB}" h="${bodySizeH}" />
    </inertial>

    <collision name='collision'>
      <origin xyz="0 0 ${wheel_height/2}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${bodySizeL} ${bodySizeB} ${bodySizeH}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <mesh filename="package://racer_description/meshes/car.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="base_body_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="body" />
  </joint>

  <link name='body'>
    <visual>
      <origin xyz="0 0 0.05" rpy=" 0 0 0"/>
      <geometry>
        <mesh filename="package://racer_description/meshes/body.dae"/>
      </geometry>
    </visual>
  </link>

    <!--  Wheels  -->
  <wheel fb="front" lr="left" parent="left_steering" translateX="1" translateY="1" left="1" OffsetJointX= "${base_x_sphere_origin_to_wheel_origin}" OffsetJointY= "${base_y_sphere_origin_to_wheel_origin}" OffsetJointZ= "${base_z_sphere_origin_to_wheel_origin}" OffsetY="0.02" />

  <wheel fb="front" lr="right" parent="right_steering" translateX="1" translateY="-1" left="0" OffsetJointX= "${base_x_sphere_origin_to_wheel_origin}" OffsetJointY= "${base_y_sphere_origin_to_wheel_origin}" OffsetJointZ= "${base_z_sphere_origin_to_wheel_origin}" OffsetY="-0.02" />

  <wheel fb="back" lr="left" parent="chassis" translateX="-1" translateY="1" left="1" OffsetJointX= "${base_x_origin_to_wheel_origin}" OffsetJointY= "${base_y_origin_to_wheel_origin}" OffsetJointZ= "${base_z_origin_to_wheel_origin}" OffsetY="0.021" />

  <wheel fb="back" lr="right" parent="chassis" translateX="-1" translateY="-1" left="0" OffsetJointX= "${base_x_origin_to_wheel_origin}" OffsetJointY= "${base_y_origin_to_wheel_origin}" OffsetJointZ= "${base_z_origin_to_wheel_origin}" OffsetY="-0.021" />

  <!-- Steering -->
  <steering_hinge lr="left" parent="chassis" translateY="1" OffsetY="0.01" />
  <steering_hinge lr="right" parent="chassis" translateY="-1" OffsetY="-0.01" />

  <!-- Camera -->
  <link name="camera">
    <inertial>
      <mass value="${cameraMass}" />
      <origin xyz="0 0 ${wheel_height/2}" rpy="0 0 0"/>
      <box_inertia m="${cameraMass}" l="${cameraSizeL}" b="${cameraSizeB}" h="${cameraSizeH}" />
    </inertial>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSizeL} ${cameraSizeH} ${cameraSizeB}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://racer_description/meshes/ZED.dae"/>
      </geometry>
    </visual>
  </link>s

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0.21 0 0.095" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="camera"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="laser">
    <inertial>
      <mass value="${hokuyoMass}" />
      <origin xyz="0 0 ${wheel_height/2}" rpy="0 0 0"/>
      <box_inertia m="${hokuyoMass}" l="${hokuyoSize}" b="${hokuyoSize}" h="${hokuyoSize}" />
    </inertial>

    <collision>
      <origin xyz="0 0 ${wheel_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${hokuyoSize} ${hokuyoSize} ${hokuyoSize}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${wheel_height/2}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://racer_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="laser_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0.21 0 0.135" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="laser"/>
  </joint>

  <!-- IMU -->
  <link name="imu_link" />

  <joint name="imu_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 0.135" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="imu_link"/>
  </joint>

</robot>
